name: "build-jdk with push to master "
on:
  push:
    branches:
      - master

jobs:
  hotspot:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04]
        javaToBuild: [jdk16u]
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      id: buildJDK
      with:
        javaToBuild: ${{ matrix.javaToBuild}}
    - run: ${{ steps.buildJDK.outputs.BuildJDKDir }}/bin/java -version
